version: '3.4'

services:
  lern-api:
    image: ${DOCKER_REGISTRY-}lernapi
    build:
      context: .
      dockerfile: Lern-API/Dockerfile
    ports:
      - 80:80
    depends_on:
      - database
    networks:
      - postgres
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: lern-dev-user
      POSTGRES_PASSWORD: lern-dev-password
      POSTGRES_DB: lern-dev-db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=lern@lernd.fr
      - PGADMIN_DEFAULT_PASSWORD=lern-dev-password
    volumes:
      - pgadmin:/pgadmin
    ports:
      - 8080:80
    networks:
      - postgres
    depends_on:
      - database

networks:
  postgres:

volumes:
  postgres:
  pgadmin:
