version: '3.4'

services:
  lern-api:
    image: ${DOCKER_REGISTRY-}lernapi
    build:
      context: .
      dockerfile: Lern-API/Dockerfile
    depends_on:
     - database
    networks:
     - postgres
     - mailhog
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: lern-dev-user
      POSTGRES_PASSWORD: lern-dev-password
      POSTGRES_DB: lern-dev-db
      PGDATA: /data/postgres
    ports:
     - 5432:5432
    volumes:
     - postgres:/data/postgres
    networks:
     - postgres
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    environment:
      MH_STORAGE: maildir
    ports:
     - 1025:1025
     - 8025:8025
    volumes:
     - mailhog:/maildir
    networks:
     - mailhog

networks:
  postgres:
  mailhog:

volumes:
  postgres:
  mailhog:
