name: .NET Core

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Lern-API.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Lern-API.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal Lern-API.sln
